---

- import_tasks: package.yml
  tags: package

- import_tasks: configuration.yml
  tags: configuration

- name: start/stop fail2ban service
  service:
    name: fail2ban
    state: '{{ fail2ban_service_state }}'
    enabled: '{{ fail2ban_service_enabled }}'
  tags: service
